import subprocess


def runExec(exec_path:str,args:str):
    command=[exec_path,args]
    # Lancer l'exécutable
    try:
        run=subprocess.run(command, check=True)
        if(run.returncode==0):
            args=args+'A'
            runExec(exec_path,args)
        
    except subprocess.CalledProcessError  as e:
        print(f"Erreur lors du lancement de l'exécutable avec la commande suivante : {exec_path} {args} ({len(args)})")
        
        

runExec("./local_exec","A"*50)